### ISSUE TITLE
Re apply terraform for xen orchestra

### ISSUE THREAD

**Issue by ddelnano** [terra-farm/terraform-github-org#4]
Since I was developing my repo on my personal account first (ddelnano/terraform-provider-xenorchestra), I deleted terra-farm/terraform-provider-xenorchestra this terraform created and then did the repo transfer. Through that import I seem to have lost the ability to access the repository settings. So I have a few comments.

1. Can you run terraform again and make sure it is ok with the transfer I did?
2. Can we restore my permissions so I can manage the settings on the repo? I'm guessing running terraform with fix this since I had the correct permissions before I deleted the repo.

cc @ringods

**Comment by ringods** [comment]
@ddelnano config fixed. You should be all set again.
